version: '3.7'
services:
  node:
    image: "${PROJECT_NAME}/node:init"
    container_name: ${PROJECT_NAME}-node
    build:
      context: ./
      dockerfile: ./containers/node/Dockerfile
      target: init
    volumes:
      - ${APP_PATH}:/app:cached
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
